--- # tasks file for net_framework

-   name: Create directory for net_framework
    win_file:
        path: C:\Users\zonedeveloper\ansible
        state: directory
    
-   name: Check if net_framework is already downloaded
    win_shell: dir {{ net_framework_location }}
    register: net_framework_found
    changed_when: net_framework_found.rc >= 1
    ignore_errors: true

-   name: Download net_framework
    win_get_url:
        url: "{{ net_framework_url }}"
        dest: "{{ net_framework_location }}"
    when: net_framework_found.rc >= 1